# Generated by Django 3.2.7 on 2022-02-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
    ]
