# Generated by Django 3.2.7 on 2022-02-22 12:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_recomendeditemsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='recomendeditemsimage',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
