# Generated by Django 3.2.7 on 2022-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20220222_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isrecomendedforyou',
            field=models.BooleanField(default=0, verbose_name='recomendeditems'),
        ),
        migrations.AddField(
            model_name='item',
            name='selectedforyou',
            field=models.BooleanField(default=0, verbose_name='selectedforyou'),
        ),
    ]
