# Generated by Django 3.2.7 on 2022-02-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedcarts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendedcart',
            old_name='item',
            new_name='recomendeditem',
        ),
    ]
