# Generated by Django 3.2.7 on 2022-02-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendeditems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendeditem',
            old_name='image',
            new_name='recomendedimage',
        ),
    ]
