# Generated by Django 3.2.7 on 2022-02-23 04:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendeditems', '0004_alter_recomendeditem_recomendedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendeditem',
            name='recomendedimage',
        ),
        migrations.AddField(
            model_name='recomendeditem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='recomendedimage'),
        ),
    ]
