# Generated by Django 3.2.7 on 2022-02-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendeditems', '0005_auto_20220223_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendeditem',
            old_name='image',
            new_name='recomendedimage',
        ),
    ]
