# Generated by Django 3.2.7 on 2022-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(db_index=True, default='size', max_length=20, verbose_name='Size'),
        ),
    ]
